### ISSUE TITLE
Class is not showing in Item Open tag

### ISSUE THREAD

**Issue by RahulSaini91** [reeazr/codeigniter-breadcrumb#2]
HTML Class tag were not showing when i implemented and after analyzing code  i found there was a static code in output (render() function) so i replace it
**Original Code:**
`$output .= '<li>';`

**Edited Code:**
`$output .= ($this->tags['itemOpen'])?$this->tags['itemOpen']:'<li>';`

now html class available in output

**Comment by reeazr** [comment]
Thank you RahulSaini91 for your contribution. I will make necessary changes.
